apiVersion: v1
kind: Service
metadata:
  labels:
    application: "connexion-example"
  name: "connexion-example-redis"
spec:
  selector:
    application: "connexion-example"
    component: redis
  type: ClusterIP
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379

