apiVersion: v1
kind: Service
metadata:
  name: connexion-example
  labels:
    application: connexion-example
spec:
  selector:
    application: connexion-example
    # select the Connexion pods (we would also match Redis pods without this label)
    component: frontend
  # use NodePort to expose service for Minikube
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080

