apiVersion: v1
kind: Service
metadata:
  labels:
    application: connexion-example
  name: connexion-example
spec:
  selector:
    application: connexion-example
    component: frontend
  # user NodePort for Minikube
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080

